# example assuming * operation is always binary

# ENV["JULIA_DEBUG"] = Metatheory

using Metatheory
using Metatheory.Library

struct NumberFoldAnalysis
  n::Number
end

Base.:(*)(a::NumberFoldAnalysis, b::NumberFoldAnalysis) = NumberFoldAnalysis(a.n * b.n)
Base.:(+)(a::NumberFoldAnalysis, b::NumberFoldAnalysis) = NumberFoldAnalysis(a.n + b.n)

# This should be auto-generated by a macro
function EGraphs.make(g::EGraph{Head,NumberFoldAnalysis}, n::ENode) where {Head}
  istree(n) || return operation(n) isa Number ? NumberFoldAnalysis(operation(n)) : nothing
  if head_symbol(head(n)) == :call && arity(n) == 2
    op = operation(n)
    args = arguments(n)
    l, r = g[args[1]], g[args[2]]

    if l.data isa NumberFoldAnalysis && r.data isa NumberFoldAnalysis
      if op == :*
        return l.data * r.data
      elseif op == :+
        return l.data + r.data
      end
    end
  end
  # Could not analyze, returns nothing
end

function EGraphs.join(from::NumberFoldAnalysis, to::NumberFoldAnalysis)
  @assert from == to
  from
end

# Add the number to the eclass.
function EGraphs.modify!(g::EGraph{Head,NumberFoldAnalysis}, eclass::EClass{NumberFoldAnalysis}) where {Head}
  isnothing(eclass.data) || union!(g, addexpr!(g, eclass.data.n), find(g, eclass.id))
end


comm_monoid = @theory begin
  ~a * ~b --> ~b * ~a
  ~a * 1 --> ~a
  ~a * (~b * ~c) --> (~a * ~b) * ~c
end

g = EGraph{ExprHead,NumberFoldAnalysis}(:(3 * 4))


@testset "Basic Constant Folding Example - Commutative Monoid" begin
  @test (true == @areequalg g comm_monoid 3 * 4 12)

  @test (true == @areequalg g comm_monoid 3 * 4 12 4 * 3 6 * 2)
end

@testset "Basic Constant Folding Example 2 - Commutative Monoid" begin
  ex = :(a * 3 * b * 4)
  g = EGraph{ExprHead,NumberFoldAnalysis}(ex)
  addexpr!(g, :(12 * a))
  @test (true == @areequalg g comm_monoid (12 * a) * b ((6 * 2) * b) * a)
  @test (true == @areequalg g comm_monoid (3 * a) * (4 * b) (12 * a) * b ((6 * 2) * b) * a)
end

@testset "Basic Constant Folding Example - Adding analysis after saturation" begin
  g = EGraph{ExprHead,NumberFoldAnalysis}(:(3 * 4))
  # addexpr!(g, 12)
  saturate!(g, comm_monoid)
  addexpr!(g, :(a * 2))
  saturate!(g, comm_monoid)

  @test (true == areequal(g, comm_monoid, :(3 * 4), 12, :(4 * 3), :(6 * 2)))

  ex = :(a * 3 * b * 4)
  g = EGraph{ExprHead,NumberFoldAnalysis}(ex)
  params = SaturationParams(timeout = 15)
  @test areequal(g, comm_monoid, :((3 * a) * (4 * b)), :((12 * a) * b), :(((6 * 2) * b) * a); params = params)
end

@testset "Infinite Loops analysis" begin
  boson = @theory begin
    1 * ~x --> ~x
  end


  g = EGraph(:(1 * x))
  params = SaturationParams(timeout = 100)
  saturate!(g, boson, params)
  ex = extract!(g, astsize)


  boson = @theory begin
    (:c * :cdag) --> :cdag * :c + 1
    ~a * (~b + ~c) --> (~a * ~b) + (~a * ~c)
    (~b + ~c) * ~a --> (~b * ~a) + (~c * ~a)
    # 1 * x => x
    (~a * ~b) * ~c --> ~a * (~b * ~c)
    ~a * (~b * ~c) --> (~a * ~b) * ~c
  end

  g = EGraph(:(c * c * cdag * cdag))
  saturate!(g, boson)
  ex = extract!(g, astsize_inv)

end

