# include("rules/patterns.jl")
export Pattern
export PatVar
export PatTerm
export PatSegment
export patvars
export setdebrujin!
export makeconsequent
export @pat
export isground
export UnsupportedPatternException