# include("rules/patterns.jl")
export AbstractPat
export PatVar
export PatTerm
export PatSegment
export patvars
export setdebrujin!
export makeconsequent
export @pat
export isground
export UnsupportedPatternException
