[package]
name = "benchmarks"
version = "0.1.0"
authors = ["0x0f0f0f <sudo-woodo3@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egg = "0.6.0"
